export const ItemMetaData = {
  spear: {
    name: 'spear',
    kind: 'weapon',
    Image: './Items/Weapons/Spear/Sprite.png',
    height: 21,
    width: 7,
    scalingFactor: 4.2,
    frame: 1,
    animationSpeed: 8,
  },
  bow: {
    name: 'bow',
    kind: 'weapon',
    Image: './Items/Weapons/Bow/SpriteS.png',
    image: '',
    height: 16,
    width: 8,
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  staff: {
    name: 'staff',
    kind: 'weapon',
    Image: '../../public/Items/Weapons/Staff/Sprite.png',
    height: 18,
    width: 6,
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  coin: {
    name: 'coin',
    kind: 'score',
    Image: './Items/Treasure/Coin2.png',
    height: 10,
    width: 10,
    scalingFactor: 3,
    frame: 4,
    score: 10,
    animationSpeed: 8
  },
  potion: {
    name: 'potion',
    kind: 'hp',
    Image: './Items/Potion/LifePot.png',
    height: 12,
    width: 10,
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8
  },
  sushi: {
    name: 'sushi',
    kind: 'food',
    Image: './Items/Food/Sushi2.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  honey: {
    name: 'honey',
    kind: 'food',
    Image: './Items/Food/Honey.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  yakitori: {
    name: 'yakitori',
    kind: 'food',
    Image: './Items/Food/Yakitori.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  onigiri: {
    name: 'onigiri',
    kind: 'food',
    Image: './Items/Food/Onigiri.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  beaf: {
    name: 'beaf',
    kind: 'food',
    Image: './Items/Food/Beaf.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  seed: {
    name: 'seed',
    kind: 'food',
    Image: './Items/Food/SeedBig1.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  fish: {
    name: 'fish',
    kind: 'food',
    Image: './Items/Food/Fish.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  cup: {
    name: 'cup',
    kind: 'score',
    Image: './Items/Treasure/GoldCup.png',
    height: 12,
    width: 12,
    scalingFactor: 4,
    frame: 1,
    score: 100,
    animationSpeed: 8,
  },
  letter: {
    name: 'letter',
    kind: 'letter',
    Image: './Items/Other/Letter.png',
    height: 12,
    width: 12,
    scalingFactor: 4,
    frame: 1,
    score: 100,
    animationSpeed: 8,
  },
}
