import { Position } from "../classes/base/positionHolder"

export const ItemSpawnList = {
  abandonedHouse: [],
  dustVale: [],
  elderWood: [],
  emeraldRift: [],
  frostSpireLake: [],
  hammerFlame: [],
  home: [new Position('spear', 850, 800)],
  house: [],
  ichiranRaman: [],
  ravenFortHall: [],
  ravenFortHall2: [],
  ravenFort: [],
  SilentVeilNecropolis: [],
  silentVeilTunnel: [],
  woodPass: [],
}

export const ItemMetaData = {
  spear: {
    name: 'spear',
    kind: 'weapon',
    Image: '../../public/Items/Weapons/Spear/Sprite.png',
    height: 21,
    width: 7,
    scalingFactor: 4.2,
    frame: 1,
    animationSpeed: 8,
  },
  bow: {
    name: 'bow',
    kind: 'weapon',
    Image: '../../public/Items/Weapons/Bow/SpriteS.png',
    image: '',
    height: 16,
    width: 8,
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  staff: {
    name: 'staff',
    kind: 'weapon',
    Image: '../../public/Items/Weapons/Staff/Sprite.png',
    height: 18,
    width: 6,
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
  coin: {
    name: 'coin',
    kind: 'score',
    Image: '../../public/Items/Treasure/Coin2.png',
    height: 10,
    width: 10,
    scalingFactor: 3,
    frame: 4,
    animationSpeed: 8
  },
  potion: {
    name: 'potion',
    kind: 'hp',
    Image: '../../public/Items/Potion/LifePot.png',
    height: 12,
    width: 10,
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8
  },
  sushi: {
    name: 'sushi',
    kind: 'hp',
    Image: '../../public/Items/Food/Sushi2.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  yakitori: {
    name: 'yakitori',
    kind: 'hp',
    Image: '../../public/Items/Food/Yakitori.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  seed: {
    name: 'seed',
    kind: 'hp',
    Image: '../../public/Items/Food/SeedBig1.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  fish: {
    name: 'fish',
    kind: 'hp',
    Image: '../../public/Items/Food/Fish.png',
    height: 16,
    width: 16,
    scalingFactor: 3.5,
    frame: 1,
    animationSpeed: 8,
  },
  cup: {
    name: 'cup',
    kind: 'special',
    Image: '../../public/Items/Treasure/GoldCup.png',
    height: 12,
    width: 12,
    scalingFactor: 4,
    frame: 1,
    animationSpeed: 8,
  },
}
