import {
  HouseDataArray,
  IchigoRamamDataArray,
  HomeDataArray,
  AbandonedHouseDataArray,
  DustValeDataArray,
  RavenFortHallDataArray,
  RavenFortHall2DataArray,
  IchiranRamamDataArray,
  HammerFlameDataArray,
  EmeraldRiftDataArray,
  ElderWoodDataArray,
  FrostSpireLakeDataArray,
  RavenFortDataArray,
  SilentVeilDataArray,
  WoodPassDataArray,
  SilentVeilTunnelDataArray,
} from "./mapdata"
import { Position } from "../classes/base/positionHolder"
import { Direction } from "../constants/direction"

export const MapMetaData = {
  home: {
    Name: 'home',
    DataArray: HomeDataArray,
    Image: Object.assign(new Image(), { src: './Map/home.png' }),
    weather: 'none',
    neighbours: [new Position('elderWood', 705, 420, Direction.down)],
  },
  house: {
    Name: 'house',
    DataArray: HouseDataArray,
    Image: Object.assign(new Image(), { src: './Map/house.png' }),
    Weather: 'none',
    neighbours: [new Position('ravenFort', 930, 805, Direction.down)],
  },
  abandonedHouse: {
    Name: 'abandonedHouse',
    DataArray: AbandonedHouseDataArray,
    Image: Object.assign(new Image(), { src: './Map/AbandonedHouse.png' }),
    Weather: 'none',
    neighbours: [new Position('dustVale', 1640, 1390, Direction.down)],
  },
  elderWood: {
    Name: 'elderWood',
    DataArray: ElderWoodDataArray,
    Image: Object.assign(new Image(), { src: './Map/Elderwood.png' }),
    Weather: 'leaf',
    neighbours: [new Position('woodPass', 350, 100, Direction.down), new Position('ichigoRaman', 650, 360, Direction.up), new Position('home', 738, 1010, Direction.up),],
  },
  woodPass: {
    Name: 'woodPass',
    DataArray: WoodPassDataArray,
    Image: Object.assign(new Image(), { src: './Map/WoodPass.png' }),
    Weather: 'leaf',
    neighbours: [new Position('elderWood', 850, 1600, Direction.up), new Position('ravenFort', 150, 750, Direction.right)],
  },
  ravenFort: {
    Name: 'ravenFort',
    DataArray: RavenFortDataArray,
    Image: Object.assign(new Image(), { src: './Map/Ravenfort.png' }),
    Weather: 'none',
    neighbours: [new Position('woodPass', 2350, 1250, Direction.left), new Position('ichiranRaman', 650, 360, Direction.up), new Position('house', 483, 420, Direction.up), new Position('emeraldRift', 340, 1670, Direction.up), new Position('ravenFortHall', 370, 420, Direction.up), new Position('frostSpireLake', 210, 1600, Direction.right), new Position('hammerFlame', 400, 420, Direction.up)],
  },
  ravenFortHall: {
    Name: 'ravenFortHall',
    DataArray: RavenFortHallDataArray,
    Image: Object.assign(new Image(), { src: './Map/Ravenforthall.png' }),
    Weather: 'none',
    neighbours: [new Position('ravenFort', 1510, 805, Direction.down), new Position('ravenFortHall2', 325, 280, Direction.left)],
  },
  ravenFortHall2: {
    Name: 'ravenFortHall2',
    DataArray: RavenFortHall2DataArray,
    Image: Object.assign(new Image(), { src: './Map/Ravenforthall2.png' }),
    Weather: 'none',
    neighbours: [new Position('ravenFortHall', 670, 310, Direction.left)],
  },
  emeraldRift: {
    Name: 'emeraldRift',
    DataArray: EmeraldRiftDataArray,
    Image: Object.assign(new Image(), { src: './Map/EmeraldRift.png' }),
    Weather: 'rain',
    neighbours: [new Position('ravenFort', 2120, 100, Direction.down), new Position('silentVeilNecropolis', 630, 100, Direction.down),],
  },
  silentVeil: {
    Name: 'silentVeilNecropolis',
    DataArray: SilentVeilDataArray,
    Image: Object.assign(new Image(), { src: './Map/SilentVeilNecropolis.png' }),
    Weather: 'heavyRain',
    neighbours: [new Position('emeraldRift', 2150, 1670, Direction.up), new Position('silentVeilTunnel', 1035, 170, Direction.down), new Position('dustVale', 150, 300, Direction.right)],
  },
  silentVeilTunnel: {
    Name: 'silentVeilTunnel',
    DataArray: SilentVeilTunnelDataArray,
    Image: Object.assign(new Image(), { src: './Map/SilentVeilTunnel.png' }),
    Weather: 'none',
    neighbours: [new Position('silentVeilNecropolis', 446, 1435, Direction.down)],
  },
  dustVale: {
    Name: 'dustVale',
    DataArray: DustValeDataArray,
    Image: Object.assign(new Image(), { src: './Map/Dustvale.png' }),
    Weather: 'leafpink',
    neighbours: [new Position('silentVeilNecropolis', 2400, 1500, Direction.left), new Position('abandonedHouse', 208, 285, Direction.right)],
  },
  frostSpireLake: {
    Name: 'frostSpireLake',
    DataArray: FrostSpireLakeDataArray,
    Image: Object.assign(new Image(), { src: './Map/FrostspireLake.png' }),
    Weather: 'snow',
    neighbours: [new Position('ravenFort', 2300, 1650, Direction.left)],
  },
  hammerFlame: {
    Name: 'hammerFlame',
    DataArray: HammerFlameDataArray,
    Image: Object.assign(new Image(), { src: '../Map/HammerFlame.png' }),
    Weather: 'none',
    neighbours: [new Position('ravenFort', 1795, 1090, Direction.down)],
  },
  ichiranRaman: {
    Name: 'ichiranRaman',
    DataArray: IchiranRamamDataArray,
    Image: Object.assign(new Image(), { src: './Map/IchiranRaman.png' }),
    Weather: 'none',
    neighbours: [new Position('ravenFort', 1120, 560, Direction.down)],
  },
  ichigoRaman: {
    Name: 'ichigoRaman',
    DataArray: IchigoRamamDataArray,
    Image: Object.assign(new Image(), { src: './Map/IchiranRaman.png' }),
    Weather: 'none',
    neighbours: [new Position('elderWood', 1660, 715, Direction.down)],
  },
}
