export const WeatherMetaData = {
  rain: {
    name: 'rain',
    Image: './FX/Particle/Rain.png',
    height: 8,
    width: 8,
    scalingFactor: 4,
    frame: 3,
    animationSpeed: 8,
    frequency: 10,
    velocity: 16,
    distance: 35,
  },
  heavyRain: {
    name: 'rain',
    Image: './FX/Particle/Rain.png',
    height: 8,
    width: 8,
    scalingFactor: 4,
    frame: 3,
    animationSpeed: 8,
    frequency: 200,
    velocity: 16,
    distance: 20,
  },
  rainOnFloor: {
    name: 'rainOnFloor',
    Image: './FX/Particle/RainOnFloor.png',
    height: 8,
    width: 8,
    scalingFactor: 3.4,
    frame: 3,
    animationSpeed: 8,
    frequency: 15,
    velocity: 0,
    distance: 20,
  },
  leaf: {
    name: 'leaf',
    Image: './FX/Particle/Leaf.png',
    height: 12,
    width: 12,
    scalingFactor: 3,
    frame: 6,
    animationSpeed: 9,
    frequency: 3,
    velocity: 0.8,
    distance: 300,
  },
  leafpink: {
    name: 'leafpink',
    Image: './FX/Particle/LeafPink.png',
    height: 12,
    width: 12,
    scalingFactor: 3,
    frame: 6,
    animationSpeed: 9,
    frequency: 3,
    velocity: 0.8,
    distance: 300,
  },
  snow: {
    name: 'snow',
    Image: './FX/Particle/Snow.png',
    height: 8,
    width: 8,
    scalingFactor: 3.8,
    frame: 7,
    animationSpeed: 6,
    frequency: 6,
    velocity: 2,
    distance: 150,
  },
}
